/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 keycapsRight.glb --transform --simplify 
Files: keycapsRight.glb [69.55KB] > keycapsRight-transformed.glb [12.56KB] (82%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshPhysicalMaterial } from "three";
import { useControls } from "leva";
import { useAnimation } from "../AnimationContext";

export default function Model() {
	const { nodes, materials } = useGLTF(
		"src/assets/keyboard/keycapsRight-transformed.glb",
	);

	const gltf = useGLTF("src/assets/keyboard/keycapsRight-transformed.glb");

	// console.log(gltf);

	const { keyCapsRef } = useAnimation();

	const config = useControls("keycaps-new", {
		visible: true,
		transparent: true,
		opacity: { value: 0.4, min: 0, max: 1, step: 0.01 },
		depthTest: true,
		depthWrite: true,
		alphaTest: { value: 0, min: 0, max: 1, step: 0.01 },
		side: {
			value: "THREE.DoubleSided",
			options: ["THREE.FrontSide", "THREE.BackSide"],
		},
		color: "#6c6c6c",
		emissive: "#000000",
		roughness: { value: 0, min: 0, max: 1, step: 0.01 },
		metalness: { value: 1, min: 0, max: 1, step: 0.01 },
		specularColor: "#ffffff",
		fog: true,
	});

	return (
		<group ref={keyCapsRef} dispose={null}>
			<mesh
				geometry={nodes.XDA_Keycaps028.geometry}
				material={materials["top housing.028"]}
				position={[134.607, -13.51, 41.067]}
				rotation={[Math.PI / 2, 0, Math.PI]}
				scale={24.637}
			>
				<meshPhysicalMaterial {...config} />
			</mesh>
			<instancedMesh
				args={[nodes.XDA_Keycaps001.geometry, null, 28]}
				instanceMatrix={nodes.XDA_Keycaps001.instanceMatrix}
			>
				<meshPhysicalMaterial {...config} />
			</instancedMesh>
		</group>
	);
}

useGLTF.preload("src/assets/keyboard/keycapsRight-transformed.glb");
