/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import proMicro from "../../../assets/keyboard/proMicro.glb";
import colourC from "../../../assets/keyboard/copperMetal/Metal047A_1K_Color.jpg";
import normalC from "../../../assets/keyboard/copperMetal/Metal047A_1K_NormalGL.jpg";
import roughnessC from "../../../assets/keyboard/copperMetal/Metal047A_1K_Roughness.jpg";
import metalC from "../../../assets/keyboard/copperMetal/Metal047A_1K_Metalness.jpg";

import colourS from "../../../assets/keyboard/brushedMetal/Metal009_1K_ColorS.jpg";
import colour from "../../../assets/keyboard/brushedMetal/Metal009_1K_Color.jpg";
import normal from "../../../assets/keyboard/brushedMetal/Metal009_1K_NormalGL.jpg";
import roughness from "../../../assets/keyboard/brushedMetal/Metal009_1K_Roughness.jpg";
import metal from "../../../assets/keyboard/brushedMetal/Metal009_1K_Metalness.jpg";
import ao from "../../../assets/keyboard/brushedMetal/Metal_Steel_Brushed_001_ambientOcclusion.jpg";
import { Color } from "three";

export default function Model(props) {
	const { nodes, materials } = useGLTF(proMicro);

	const copperMetal = useTexture({
		map: colourC, // colour map
		normalMap: normalC,
		roughnessMap: roughnessC,
		metalnessMap: metalC,
		// aoMap: aoC,
	});

	const brushedMetalS = useTexture({
		map: colourS, // colour map
		normalMap: normal,
		roughnessMap: roughness,
		metalnessMap: metal,
		aoMap: ao,
	});

	const white = new Color(0xffffff);
	const black = new Color(0x000000);
	const blue = new Color(0xff0000);

	return (
		<group {...props} dispose={null}>
			{/* prettier-ignore */}
			<group position={[18.0576, -30.106, -39.593]}> 
                {/* change position of group  */}
        <group >
            <mesh geometry={nodes.writing001.geometry} material={nodes.writing001.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={white} /></mesh>
            <mesh geometry={nodes.writing002.geometry} material={nodes.writing002.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={white} /></mesh>
            <mesh geometry={nodes.writing.geometry} material={nodes.writing.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={white} /></mesh>
            <mesh geometry={nodes.writing003.geometry} material={nodes.writing003.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={white} /></mesh>
            <mesh geometry={nodes.writing004.geometry} material={nodes.writing004.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={white} /></mesh>
            <mesh geometry={nodes.writing005.geometry} material={nodes.writing005.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={white} /></mesh>
            <mesh geometry={nodes.writing006.geometry} material={nodes.writing006.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={white} /></mesh>
            <mesh geometry={nodes.writing007.geometry} material={nodes.writing007.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={white} /></mesh>
            <mesh geometry={nodes.writing008.geometry} material={nodes.writing008.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={white} /></mesh>
        </group>
        <group >
            <mesh geometry={nodes.pads001.geometry} material={nodes.pads001.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads002.geometry} material={nodes.pads002.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pad.geometry} material={nodes.pad.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads003.geometry} material={nodes.pads003.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads004.geometry} material={nodes.pads004.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads006.geometry} material={nodes.pads006.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads007.geometry} material={nodes.pads007.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads009.geometry} material={nodes.pads009.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads008.geometry} material={nodes.pads008.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads010.geometry} material={nodes.pads010.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads011.geometry} material={nodes.pads011.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads012.geometry} material={nodes.pads012.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads013.geometry} material={nodes.pads013.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads014.geometry} material={nodes.pads014.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads015.geometry} material={nodes.pads015.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads016.geometry} material={nodes.pads016.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads017.geometry} material={nodes.pads017.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads018.geometry} material={nodes.pads018.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.contact005.geometry} material={nodes.contact005.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.contacts001.geometry} material={nodes.contacts001.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.pads.geometry} material={nodes.pads.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.contact006.geometry} material={nodes.contact006.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.contact001.geometry} material={nodes.contact001.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.contact002.geometry} material={nodes.contact002.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.contact003.geometry} material={nodes.contact003.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.contact004.geometry} material={nodes.contact004.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
            <mesh geometry={nodes.contact.geometry} material={nodes.contact.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...brushedMetalS} metalness={1} /></mesh>
        </group>
        <group >
            <mesh geometry={nodes.contacts.geometry} material={nodes.contacts.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...copperMetal} metalness={1} /></mesh>
            <mesh geometry={nodes.contacts002.geometry} material={nodes.contacts002.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...copperMetal} metalness={1} /></mesh>
            <mesh geometry={nodes.contacts003.geometry} material={nodes.contacts003.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...copperMetal} metalness={1} /></mesh>
            <mesh geometry={nodes.contact007.geometry} material={nodes.contact007.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial {...copperMetal} metalness={1} /></mesh>
        </group>
        <group>
            <mesh geometry={nodes.chip002.geometry} material={nodes.chip002.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip001.geometry} material={nodes.chip001.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip003.geometry} material={nodes.chip003.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip004.geometry} material={nodes.chip004.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip005.geometry} material={nodes.chip005.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip006.geometry} material={nodes.chip006.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip007.geometry} material={nodes.chip007.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip008.geometry} material={nodes.chip008.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip009.geometry} material={nodes.chip009.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip010.geometry} material={nodes.chip010.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip011.geometry} material={nodes.chip011.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip013.geometry} material={nodes.chip013.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip012.geometry} material={nodes.chip012.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip014.geometry} material={nodes.chip014.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip015.geometry} material={nodes.chip015.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chips001.geometry} material={nodes.chips001.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip016.geometry} material={nodes.chip016.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip017.geometry} material={nodes.chip017.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chips.geometry} material={nodes.chips.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip018.geometry} material={nodes.chip018.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip019.geometry} material={nodes.chip019.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip020.geometry} material={nodes.chip020.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip021.geometry} material={nodes.chip021.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip022.geometry} material={nodes.chip022.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
            <mesh geometry={nodes.chip.geometry} material={nodes.chip.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={black} /></mesh>
        </group>
                <mesh geometry={nodes.pcb.geometry} material={nodes.pcb.material} rotation={[Math.PI / 2, 0, Math.PI / 2]} ><meshStandardMaterial color={blue} metalness={0.8} /></mesh>
      </group>
		</group>
	);
}

useGLTF.preload("/proMicro.glb");
