/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import rotary from "../../../assets/keyboard/rotary.glb";

import colourS from "../../../assets/keyboard/brushedMetal/Metal009_1K_ColorS.jpg";
import colour from "../../../assets/keyboard/brushedMetal/Metal009_1K_Color.jpg";
import normal from "../../../assets/keyboard/brushedMetal/Metal009_1K_NormalGL.jpg";
import roughness from "../../../assets/keyboard/brushedMetal/Metal009_1K_Roughness.jpg";
import metal from "../../../assets/keyboard/brushedMetal/Metal009_1K_Metalness.jpg";
import ao from "../../../assets/keyboard/brushedMetal/Metal_Steel_Brushed_001_ambientOcclusion.jpg";

export default function Model(props) {
	const { nodes, materials } = useGLTF(rotary);

	const brushedMetal = useTexture({
		map: colour, // colour map
		normalMap: normal,
		roughnessMap: roughness,
		metalnessMap: metal,
		aoMap: ao,
	});
	const brushedMetalS = useTexture({
		map: colourS, // colour map
		normalMap: normal,
		roughnessMap: roughness,
		metalnessMap: metal,
		aoMap: ao,
	});

	// useLayoutEffect(() => {
	// Object.assign(nodes.Cylinder.material, {
	// 	...brushedMetal,
	// 	// });
	// 	Object.assign(nodes.imagetostl_mesh001.material, {
	// 		...brushedMetalS,
	// 	});
	// });

	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Cylinder.geometry}
				// material={nodes.Cylinder.material}
				position={[24.57, -14.18, 11.95]}
				rotation={[-Math.PI, 0, 0]}
				scale={12.67}
			>
				<meshStandardMaterial {...brushedMetal} metalness={1} />
			</mesh>
			<mesh
				geometry={nodes.imagetostl_mesh001.geometry}
				// material={nodes.imagetostl_mesh001.material}
				position={[24.57, -21.41, 12.89]}
				rotation={[1.57, 0, 0]}
			>
				<meshStandardMaterial {...brushedMetalS} metalness={1} />
			</mesh>
			<mesh
				// two contact
				geometry={nodes.imagetostl_mesh002.geometry}
				material={nodes.imagetostl_mesh002.material}
				position={[24.57, -21.41, 12.89]}
				rotation={[1.57, 0, 0]}
			/>
			<mesh
				// two contact
				geometry={nodes.imagetostl_mesh003.geometry}
				material={nodes.imagetostl_mesh003.material}
				position={[24.57, -21.41, 12.89]}
				rotation={[1.57, 0, 0]}
			/>
			<mesh
				// three contact
				geometry={nodes.imagetostl_mesh004.geometry}
				material={nodes.imagetostl_mesh004.material}
				position={[24.57, -21.41, 12.89]}
				rotation={[1.57, 0, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/rotary.glb");
