/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import springs from "../../../assets/keyboard/springs.glb";
export default function Model(props) {
	const { nodes, materials } = useGLTF(springs);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Body1176.geometry}
				material={materials["Steel - Satin.031"]}
				position={[29.07, -21.9, 42.5]}
				rotation={[3.14, -0.47, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1164.geometry}
				material={materials["Steel - Satin.031"]}
				position={[110.39, -21.9, 41.88]}
				rotation={[0, 1.29, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1173.geometry}
				material={materials["Steel - Satin.031"]}
				position={[134.54, -21.9, 41.09]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1161.geometry}
				material={materials["Steel - Satin.031"]}
				position={[91.22, -21.9, 37.9]}
				rotation={[0.01, 1.48, 3.13]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1152.geometry}
				material={materials["Steel - Satin.031"]}
				position={[71.92, -21.9, 37.73]}
				rotation={[3.13, 1.52, 0.01]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1149.geometry}
				material={materials["Steel - Satin.031"]}
				position={[52.77, -21.9, 40.33]}
				rotation={[3.14, 1.36, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1140.geometry}
				material={materials["Steel - Satin.031"]}
				position={[47.55, -21.9, 3.09]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1137.geometry}
				material={materials["Steel - Satin.031"]}
				position={[47.55, -21.9, -14.72]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1128.geometry}
				material={materials["Steel - Satin.031"]}
				position={[47.55, -21.9, -32.53]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1122.geometry}
				material={materials["Steel - Satin.031"]}
				position={[47.58, -21.9, 20.93]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1007.geometry}
				material={materials["Steel - Satin.031"]}
				position={[83.25, -21.9, 16.47]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1005.geometry}
				material={materials["Steel - Satin.031"]}
				position={[101.07, -21.9, 18.83]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1017.geometry}
				material={materials["Steel - Satin.031"]}
				position={[118.93, -21.9, 23.19]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1020.geometry}
				material={materials["Steel - Satin.031"]}
				position={[136.74, -21.9, 23.19]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1029.geometry}
				material={materials["Steel - Satin.031"]}
				position={[136.74, -21.9, 5.36]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1032.geometry}
				material={materials["Steel - Satin.031"]}
				position={[136.74, -21.9, -12.44]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1041.geometry}
				material={materials["Steel - Satin.031"]}
				position={[136.74, -21.9, -30.25]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1044.geometry}
				material={materials["Steel - Satin.031"]}
				position={[118.9, -21.9, -30.25]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1053.geometry}
				material={materials["Steel - Satin.031"]}
				position={[118.9, -21.9, -12.44]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1056.geometry}
				material={materials["Steel - Satin.031"]}
				position={[118.9, -21.9, 5.36]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1065.geometry}
				material={materials["Steel - Satin.031"]}
				position={[101.09, -21.9, 0.97]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1068.geometry}
				material={materials["Steel - Satin.031"]}
				position={[101.09, -21.9, -16.84]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1077.geometry}
				material={materials["Steel - Satin.031"]}
				position={[101.09, -21.9, -34.65]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1080.geometry}
				material={materials["Steel - Satin.031"]}
				position={[83.23, -21.9, -36.99]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1089.geometry}
				material={materials["Steel - Satin.031"]}
				position={[83.23, -21.9, -19.18]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1092.geometry}
				material={materials["Steel - Satin.031"]}
				position={[83.23, -21.9, -1.37]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1101.geometry}
				material={materials["Steel - Satin.031"]}
				position={[65.41, -21.9, 0.94]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1104.geometry}
				material={materials["Steel - Satin.031"]}
				position={[65.41, -21.9, -16.86]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1113.geometry}
				material={materials["Steel - Satin.031"]}
				position={[65.41, -21.9, -34.67]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1119.geometry}
				material={materials["Steel - Satin.031"]}
				position={[65.43, -21.9, 18.78]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
		</group>
	);
}

useGLTF.preload("/springs.glb");
