/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import stem from "../../../assets/keyboard/stem.glb";

export default function Model(props) {
	const { nodes, materials } = useGLTF(stem);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Body1178.geometry}
				material={materials["Stem.028"]}
				position={[29.09, -16.64, 42.48]}
				rotation={[1.57, 0, 1.1]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1166.geometry}
				material={materials["Stem.028"]}
				position={[110.39, -16.64, 41.9]}
				rotation={[1.57, 0, -2.86]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1171.geometry}
				material={materials["Stem.028"]}
				position={[134.55, -16.64, 41.11]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1159.geometry}
				material={materials["Stem.028"]}
				position={[91.22, -16.64, 37.92]}
				rotation={[1.57, 0, -3.05]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1154.geometry}
				material={materials["Stem.028"]}
				position={[71.92, -16.64, 37.75]}
				rotation={[1.57, 0, 3.09]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1147.geometry}
				material={materials["Stem.028"]}
				position={[52.78, -16.64, 40.35]}
				rotation={[1.57, 0, 2.93]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1142.geometry}
				material={materials["Stem.028"]}
				position={[47.56, -16.64, 3.11]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1135.geometry}
				material={materials["Stem.028"]}
				position={[47.56, -16.64, -14.7]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1130.geometry}
				material={materials["Stem.028"]}
				position={[47.56, -16.64, -32.51]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1124.geometry}
				material={materials["Stem.028"]}
				position={[47.58, -16.64, 20.94]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1009.geometry}
				material={materials["Stem.028"]}
				position={[83.26, -16.64, 16.48]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1003.geometry}
				material={materials["Stem.028"]}
				position={[101.07, -16.64, 18.85]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1015.geometry}
				material={materials["Stem.028"]}
				position={[118.93, -16.64, 23.21]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1022.geometry}
				material={materials["Stem.028"]}
				position={[136.74, -16.64, 23.21]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1027.geometry}
				material={materials["Stem.028"]}
				position={[136.74, -16.64, 5.38]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1034.geometry}
				material={materials["Stem.028"]}
				position={[136.74, -16.64, -12.42]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1039.geometry}
				material={materials["Stem.028"]}
				position={[136.74, -16.64, -30.23]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1046.geometry}
				material={materials["Stem.028"]}
				position={[118.9, -16.64, -30.23]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1051.geometry}
				material={materials["Stem.028"]}
				position={[118.9, -16.64, -12.42]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1058.geometry}
				material={materials["Stem.028"]}
				position={[118.9, -16.64, 5.38]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1063.geometry}
				material={materials["Stem.028"]}
				position={[101.09, -16.64, 0.99]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1070.geometry}
				material={materials["Stem.028"]}
				position={[101.09, -16.64, -16.82]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1075.geometry}
				material={materials["Stem.028"]}
				position={[101.09, -16.64, -34.63]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1082.geometry}
				material={materials["Stem.028"]}
				position={[83.23, -16.64, -36.97]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1087.geometry}
				material={materials["Stem.028"]}
				position={[83.23, -16.64, -19.16]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1094.geometry}
				material={materials["Stem.028"]}
				position={[83.23, -16.64, -1.35]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1099.geometry}
				material={materials["Stem.028"]}
				position={[65.41, -16.64, 0.96]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1106.geometry}
				material={materials["Stem.028"]}
				position={[65.41, -16.64, -16.84]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1111.geometry}
				material={materials["Stem.028"]}
				position={[65.41, -16.64, -34.66]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1117.geometry}
				material={materials["Stem.028"]}
				position={[65.44, -16.64, 18.8]}
				rotation={[1.57, 0, 3.14]}
				scale={9.38}
			/>
		</group>
	);
}

useGLTF.preload("/stem.glb");
