import { useState } from "react";
import {
  Accordion,
  AccordionHeader,
  AccordionBody,
} from "@material-tailwind/react";
import { Helmet } from "react-helmet-async";

export default function Example() {
  const [open, setOpen] = useState(0);

  const handleOpen = (value) => {
    setOpen(open === value ? 0 : value);
  };

  let faqs = [
    {
      question: "What is CHIP Poker?", // vision
      answer:
        "CHIP poker is a digitally autonamous organisation (DAO) that seeks to deliver provably fair peer to peer Texas Hold 'em on the Polygon network. \n\nPlayers will be able to play against friends, or people, from all around the world. CHIP will be fully dentralised, permissionless, trustless and provably fair offering a unique take on poker.",
    },
    {
      question: "What does being a DAO mean?", // vision
      answer:
        "DAO stands for digitally autonomous organisation. \n\nThis means that you as the user get to help make the important decisions that shape the future of CHIP poker. There will be a native token that can be used to vote on snapshot proposals. This will allow users to make decisions about the future of their casino.",
    },
    {
      question: "Where will CHIP poker exist?",
      answer:
        "CHIP poker will be designed and tested on the Polygon network with plans to expand. We chose Polygon because of its incredible throughput and negligible cost per transaction. Polygon is an EVM compatible blockchain meaning we can launch on many different layer twos with ease.",
    },
    {
      question: "Will there be a token?", // vision
      answer:
        "CHIP poker will have a native token that users can buy. With these tokens users can stake them to earn 90% of the rake generated by CHIP poker preportional to their staked amount. Users will also be able to vote on snapshot proposals, your vote will be preportional to the amount of tokens you hold, giving large investors more say in the direction of CHIP.",
    },
    {
      question: "Where can I buy CHIP?", // mission
      answer:
        "The first offering will be on the sushiswap ecosystem on their ICO platform MISO. More information will be launched on the discord soon.",
    },
    {
      question: "How is CHIP different to other casions?",
      answer:
        "Chip will never hold your funds. When you sit at a table a transaction will send tokens out of your wallet and into our smart contract. This works in reverse for frictionless and permissionless instant withdrawals.",
    },
    {
      question: "Am I in control of my money at all times?",
      answer:
        "Yes, due to the nature of interacting with smart contracts only the wallet that sent funds to the smart contract can request the back. \n\nThis, we believe, creates a safe place where users can play with money directly from their wallet and have that money back in their wallet when they are finished playing. In the even of a loss of connectivity only your wallet will be able to access funds stored in CHIP contracts.",
    },
    {
      question: "How do I deposit funds?",
      answer:
        "Tokens will be depositted directly into the table you want to play at. The tokens will be sent from your wallet into our smart contract and allow you to use them at the table. Each table is a smart contract so tokens need to be sent to each one individually.",
    },
    {
      question: "How do I withdraw funds?",
      answer:
        "When you are finished playing at a table, you will be able to settle your funds instantly on your way out. If there is a loss of connectivity or you forget, only the wallet that depositted the funds will be able to withdraw them at a later stage.",
    },

    {
      question: "How do CHIP Tokens generate yield?",
      answer:
        "By staking your CHIP tokens on our platform you will receive 90% of the protocol generated revenue relative to your tokens staked.",
    },

    {
      question: "Do I need to KYC to play?",
      answer:
        "No - all you will need is a wallet and some tokens. There is no signup or user account at all.",
    },
    {
      question: "Are there Cash Games and Tournaments?",
      answer:
        "Most of our games are cash games. A player will use tokens directly from their wallet. There will also be tournaments with big prize pools in our native token. ",
    },
    {
      question: "How much can I start playing with?",
      answer:
        "As little as 1$ should be enough to play your first hand. There will be a very large market cap on the CHIP token allowing smaller games to be played without having to play with decimal ammounts.",
    },
    { question: "What is the rake CHIP takes?", answer: "5% up to 2$" },
  ];

  return (
    <div className="mx-[10px] min-h-[100vh] text-left md:mx-[20vw] lg:mx-[27vw]">
      <Helmet>
        <title>CHIP poker | About</title>
        <meta
          name="description"
          content="CHIP poker is a digitally autonamous organisation (DAO) that seeks to deliver provably fair peer to peer Texas Hold 'em on the Polygon network."
        />
      </Helmet>
      {faqs.map((faq, index) => (
        <Accordion
          open={open === index + 1}
          onClick={() => handleOpen(index + 1)}
          className="z-10 m-2 font-semibold text-white backdrop-blur-md"
          key={index}
        >
          <AccordionHeader className="leading-wide rounded-t-xl bg-[#ffffff11] p-4 text-3xl text-white shadow-md backdrop-blur-md ">
            {`${index + 1}) ${faq.question}`}
          </AccordionHeader>
          <AccordionBody className="whitespace-pre-wrap rounded-b-xl  bg-[rgba(255,255,255,0.03)] p-10 text-xl font-semibold">
            {faq.answer}
          </AccordionBody>
        </Accordion>
      ))}
    </div>
  );
}
