/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import bottomHousing from "../../assets/keyboard/bottomHousing.glb";

export default function Model(props) {
	const { nodes, materials } = useGLTF(bottomHousing);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Body1180.geometry}
				material={materials["Sweet Plastic.031"]}
				position={[29.11, -23.12, 42.48]}
				rotation={[3.14, -0.47, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1168.geometry}
				material={materials["Sweet Plastic.028"]}
				position={[110.38, -23.12, 41.92]}
				rotation={[0, 1.29, 3.14]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1169.geometry}
				material={materials["Sweet Plastic.030"]}
				position={[134.54, -23.12, 41.13]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1157.geometry}
				material={materials["Sweet Plastic.027"]}
				position={[91.21, -23.12, 37.94]}
				rotation={[0.01, 1.48, 3.13]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1156.geometry}
				material={materials["Sweet Plastic.026"]}
				position={[71.92, -23.12, 37.77]}
				rotation={[3.13, 1.52, 0.01]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1145.geometry}
				material={materials["Sweet Plastic.025"]}
				position={[52.78, -23.12, 40.37]}
				rotation={[3.14, 1.36, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1144.geometry}
				material={materials["Sweet Plastic.024"]}
				position={[47.55, -23.12, 3.13]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1133.geometry}
				material={materials["Sweet Plastic.023"]}
				position={[47.55, -23.12, -14.68]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1132.geometry}
				material={materials["Sweet Plastic.022"]}
				position={[47.55, -23.12, -32.49]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1126.geometry}
				material={materials["Sweet Plastic.021"]}
				position={[47.58, -23.12, 20.96]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1011.geometry}
				material={materials["Sweet Plastic"]}
				position={[83.25, -23.12, 16.5]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1001.geometry}
				material={materials["Sweet Plastic.002"]}
				position={[101.06, -23.12, 18.87]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1013.geometry}
				material={materials["Sweet Plastic.003"]}
				position={[118.93, -23.12, 23.23]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1024.geometry}
				material={materials["Sweet Plastic.004"]}
				position={[136.74, -23.12, 23.23]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1025.geometry}
				material={materials["Sweet Plastic.005"]}
				position={[136.74, -23.12, 5.4]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1036.geometry}
				material={materials["Sweet Plastic.006"]}
				position={[136.74, -23.12, -12.4]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1037.geometry}
				material={materials["Sweet Plastic.007"]}
				position={[136.74, -23.12, -30.21]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1048.geometry}
				material={materials["Sweet Plastic.008"]}
				position={[118.9, -23.12, -30.21]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1049.geometry}
				material={materials["Sweet Plastic.009"]}
				position={[118.9, -23.12, -12.4]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1060.geometry}
				material={materials["Sweet Plastic.010"]}
				position={[118.9, -23.12, 5.4]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1061.geometry}
				material={materials["Sweet Plastic.011"]}
				position={[101.09, -23.12, 1]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1072.geometry}
				material={materials["Sweet Plastic.012"]}
				position={[101.09, -23.12, -16.8]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1073.geometry}
				material={materials["Sweet Plastic.013"]}
				position={[101.09, -23.12, -34.61]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1084.geometry}
				material={materials["Sweet Plastic.014"]}
				position={[83.22, -23.12, -36.95]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1085.geometry}
				material={materials["Sweet Plastic.015"]}
				position={[83.22, -23.12, -19.14]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1096.geometry}
				material={materials["Sweet Plastic.016"]}
				position={[83.22, -23.12, -1.34]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1097.geometry}
				material={materials["Sweet Plastic.017"]}
				position={[65.4, -23.12, 0.98]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1108.geometry}
				material={materials["Sweet Plastic.018"]}
				position={[65.4, -23.12, -16.83]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1109.geometry}
				material={materials["Sweet Plastic.019"]}
				position={[65.4, -23.12, -34.64]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1115.geometry}
				material={materials["Sweet Plastic.020"]}
				position={[65.43, -23.12, 18.82]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			/>
		</group>
	);
}

useGLTF.preload("/bottomHousing.glb");
