/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import contacts from "../../assets/keyboard/contacts.glb";

export default function Model(props) {
	const { nodes, materials } = useGLTF(contacts);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Body1177.geometry}
				material={materials["Gold Damaged.030"]}
				position={[27.33, -23.34, 44.98]}
				rotation={[1.57, 0, -2.04]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2030.geometry}
				material={materials["Gold Damaged.030"]}
				position={[24.96, -21.49, 44.36]}
				rotation={[1.57, 0, -2.04]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1165.geometry}
				material={materials["Gold Damaged.030"]}
				position={[109.78, -23.34, 38.91]}
				rotation={[1.57, 0, 0.28]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2028.geometry}
				material={materials["Gold Damaged.030"]}
				position={[111.85, -21.49, 37.6]}
				rotation={[1.57, 0, 0.28]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1172.geometry}
				material={materials["Gold Damaged.030"]}
				position={[133.12, -23.34, 38.41]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2029.geometry}
				material={materials["Gold Damaged.030"]}
				position={[134.75, -21.49, 36.58]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1160.geometry}
				material={materials["Gold Damaged.030"]}
				position={[90.04, -23.34, 35.1]}
				rotation={[1.57, 0, 0.09]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2027.geometry}
				material={materials["Gold Damaged.030"]}
				position={[91.83, -21.49, 33.42]}
				rotation={[1.57, 0, 0.09]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1153.geometry}
				material={materials["Gold Damaged.030"]}
				position={[70.36, -23.34, 35.12]}
				rotation={[1.57, 0, -0.05]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2026.geometry}
				material={materials["Gold Damaged.030"]}
				position={[71.89, -21.49, 33.21]}
				rotation={[1.57, 0, -0.05]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1148.geometry}
				material={materials["Gold Damaged.030"]}
				position={[50.83, -23.34, 38]}
				rotation={[1.57, 0, -0.21]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2025.geometry}
				material={materials["Gold Damaged.030"]}
				position={[52.04, -21.49, 35.87]}
				rotation={[1.57, 0, -0.21]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1141.geometry}
				material={materials["Gold Damaged.030"]}
				position={[46.13, -23.34, 0.4]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2024.geometry}
				material={materials["Gold Damaged.030"]}
				position={[47.76, -21.49, -1.43]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1136.geometry}
				material={materials["Gold Damaged.030"]}
				position={[46.13, -23.34, -17.4]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2023.geometry}
				material={materials["Gold Damaged.030"]}
				position={[47.76, -21.49, -19.23]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1129.geometry}
				material={materials["Gold Damaged.030"]}
				position={[46.13, -23.34, -35.21]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2022.geometry}
				material={materials["Gold Damaged.030"]}
				position={[47.76, -21.49, -37.04]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1123.geometry}
				material={materials["Gold Damaged.030"]}
				position={[46.16, -23.34, 18.24]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2021.geometry}
				material={materials["Gold Damaged.030"]}
				position={[47.79, -21.49, 16.41]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1008.geometry}
				material={materials["Gold Damaged.030"]}
				position={[81.83, -23.34, 13.78]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2001.geometry}
				material={materials["Gold Damaged.030"]}
				position={[83.46, -21.49, 11.95]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1004.geometry}
				material={materials["Gold Damaged.030"]}
				position={[99.65, -23.34, 16.15]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2002.geometry}
				material={materials["Gold Damaged.030"]}
				position={[101.27, -21.49, 14.31]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1016.geometry}
				material={materials["Gold Damaged.030"]}
				position={[117.51, -23.34, 20.5]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2003.geometry}
				material={materials["Gold Damaged.030"]}
				position={[119.14, -21.49, 18.67]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1021.geometry}
				material={materials["Gold Damaged.030"]}
				position={[135.32, -23.34, 20.5]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2004.geometry}
				material={materials["Gold Damaged.030"]}
				position={[136.95, -21.49, 18.67]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1028.geometry}
				material={materials["Gold Damaged.030"]}
				position={[135.32, -23.34, 2.68]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2005.geometry}
				material={materials["Gold Damaged.030"]}
				position={[136.95, -21.49, 0.85]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1033.geometry}
				material={materials["Gold Damaged.030"]}
				position={[135.32, -23.34, -15.12]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2006.geometry}
				material={materials["Gold Damaged.030"]}
				position={[136.95, -21.49, -16.95]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1040.geometry}
				material={materials["Gold Damaged.030"]}
				position={[135.32, -23.34, -32.94]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2007.geometry}
				material={materials["Gold Damaged.030"]}
				position={[136.95, -21.49, -34.77]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1045.geometry}
				material={materials["Gold Damaged.030"]}
				position={[117.48, -23.34, -32.94]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2008.geometry}
				material={materials["Gold Damaged.030"]}
				position={[119.11, -21.49, -34.77]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1052.geometry}
				material={materials["Gold Damaged.030"]}
				position={[117.48, -23.34, -15.12]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2009.geometry}
				material={materials["Gold Damaged.030"]}
				position={[119.11, -21.49, -16.95]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1057.geometry}
				material={materials["Gold Damaged.030"]}
				position={[117.48, -23.34, 2.68]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2010.geometry}
				material={materials["Gold Damaged.030"]}
				position={[119.11, -21.49, 0.85]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1064.geometry}
				material={materials["Gold Damaged.030"]}
				position={[99.67, -23.34, -1.72]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2011.geometry}
				material={materials["Gold Damaged.030"]}
				position={[101.3, -21.49, -3.55]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1069.geometry}
				material={materials["Gold Damaged.030"]}
				position={[99.67, -23.34, -19.52]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2012.geometry}
				material={materials["Gold Damaged.030"]}
				position={[101.3, -21.49, -21.35]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1076.geometry}
				material={materials["Gold Damaged.030"]}
				position={[99.67, -23.34, -37.33]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2013.geometry}
				material={materials["Gold Damaged.030"]}
				position={[101.3, -21.49, -39.16]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1081.geometry}
				material={materials["Gold Damaged.030"]}
				position={[81.81, -23.34, -39.67]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2014.geometry}
				material={materials["Gold Damaged.030"]}
				position={[83.43, -21.49, -41.5]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1088.geometry}
				material={materials["Gold Damaged.030"]}
				position={[81.81, -23.34, -21.86]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2015.geometry}
				material={materials["Gold Damaged.030"]}
				position={[83.43, -21.49, -23.69]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1093.geometry}
				material={materials["Gold Damaged.030"]}
				position={[81.81, -23.34, -4.06]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2016.geometry}
				material={materials["Gold Damaged.030"]}
				position={[83.43, -21.49, -5.89]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1100.geometry}
				material={materials["Gold Damaged.030"]}
				position={[63.99, -23.34, -1.74]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2017.geometry}
				material={materials["Gold Damaged.030"]}
				position={[65.61, -21.49, -3.57]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1105.geometry}
				material={materials["Gold Damaged.030"]}
				position={[63.99, -23.34, -19.55]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2018.geometry}
				material={materials["Gold Damaged.030"]}
				position={[65.61, -21.49, -21.38]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1112.geometry}
				material={materials["Gold Damaged.030"]}
				position={[63.99, -23.34, -37.36]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2019.geometry}
				material={materials["Gold Damaged.030"]}
				position={[65.61, -21.49, -39.19]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1118.geometry}
				material={materials["Gold Damaged.030"]}
				position={[64.01, -23.34, 16.09]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body2020.geometry}
				material={materials["Gold Damaged.030"]}
				position={[65.64, -21.49, 14.26]}
				rotation={[1.57, 0, 0]}
				scale={9.38}
			/>
		</group>
	);
}

useGLTF.preload("/contacts.glb");
