/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import housing from "../../assets/keyboard/housing.glb";

export default function Model(props) {
	const { nodes, materials } = useGLTF(housing);
	const config = useControls("housing middle", {
		visible: true,
		transparent: true,
		opacity: { value: 0.4, min: 0, max: 1, step: 0.01 },
		depthTest: true,
		depthWrite: false,
		alphaTest: { value: 0, min: 0, max: 1, step: 0.01 },
		side: {
			value: "THREE.DoubleSided",
			options: ["THREE.FrontSide", "THREE.BackSide"],
		},
		color: "#c0c0c0",
		emissive: "#000000",
		roughness: { value: 1, min: 0, max: 1, step: 0.01 },
		metalness: { value: 0, min: 0, max: 1, step: 0.01 },
		specularColor: "#ffffff",
		fog: true,
	});
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes["middle_(right)"].geometry}
				material={nodes["middle_(right)"].material}
				position={[82.7, -27.59, 18.02]}
				rotation={[Math.PI, 0, Math.PI]}
				scale={[1, 3, 1]}
			>
				<meshPhysicalMaterial {...config} />{" "}
			</mesh>
			<mesh
				geometry={nodes["top_(right)_fixed_simple_geo"].geometry}
				material={nodes["top_(right)_fixed_simple_geo"].material}
				position={[83.88, -22.55, 6.7]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
			<mesh
				geometry={nodes["bottom_(right)"].geometry}
				material={nodes["bottom_(right)"].material}
				position={[78.33, -32.54, 21.43]}
				rotation={[Math.PI, 0, Math.PI]}
			/>
		</group>
	);
}

useGLTF.preload("/housing.glb");
