/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import rotary from "../../assets/keyboard/rotary.glb";

export default function Model(props) {
	const { nodes, materials } = useGLTF(rotary);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Cylinder.geometry}
				material={nodes.Cylinder.material}
				position={[24.57, -15.18, 11.95]}
				rotation={[-Math.PI, 0, 0]}
				scale={12.67}
			/>
			<mesh
				geometry={nodes.imagetostl_mesh001.geometry}
				material={nodes.imagetostl_mesh001.material}
				position={[24.57, -22.41, 12.89]}
				rotation={[1.57, 0, 0]}
			/>
			<mesh
				geometry={nodes.imagetostl_mesh002.geometry}
				material={nodes.imagetostl_mesh002.material}
				position={[24.57, -22.41, 12.89]}
				rotation={[1.57, 0, 0]}
			/>
			<mesh
				geometry={nodes.imagetostl_mesh003.geometry}
				material={nodes.imagetostl_mesh003.material}
				position={[24.57, -22.41, 12.89]}
				rotation={[1.57, 0, 0]}
			/>
			<mesh
				geometry={nodes.imagetostl_mesh004.geometry}
				material={nodes.imagetostl_mesh004.material}
				position={[24.57, -22.41, 12.89]}
				rotation={[1.57, 0, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/rotary.glb");
