/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import stemClick from "../../assets/keyboard/stemClick.glb";

export default function Model(props) {
	const { nodes, materials } = useGLTF(stemClick);
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Body1175.geometry}
				material={materials["Stem.028"]}
				position={[28.92, -20.05, 42.57]}
				rotation={[1.57, 0, -0.47]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1163.geometry}
				material={materials["Stem.028"]}
				position={[110.44, -20.05, 41.72]}
				rotation={[1.57, 0, 1.85]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1174.geometry}
				material={materials["Stem.028"]}
				position={[134.54, -20.05, 40.93]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1162.geometry}
				material={materials["Stem.028"]}
				position={[91.23, -20.05, 37.73]}
				rotation={[1.57, 0, 1.66]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1151.geometry}
				material={materials["Stem.028"]}
				position={[71.91, -20.05, 37.57]}
				rotation={[1.57, 0, 1.52]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1150.geometry}
				material={materials["Stem.028"]}
				position={[52.74, -20.05, 40.17]}
				rotation={[1.57, 0, 1.36]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1139.geometry}
				material={materials["Stem.028"]}
				position={[47.55, -20.05, 2.92]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1138.geometry}
				material={materials["Stem.028"]}
				position={[47.55, -20.05, -14.88]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1127.geometry}
				material={materials["Stem.028"]}
				position={[47.55, -20.05, -32.7]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1121.geometry}
				material={materials["Stem.028"]}
				position={[47.58, -20.05, 20.76]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1006.geometry}
				material={materials["Stem.028"]}
				position={[83.25, -20.05, 16.3]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1012.geometry}
				material={materials["Stem.028"]}
				position={[101.06, -20.05, 18.66]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1018.geometry}
				material={materials["Stem.028"]}
				position={[118.93, -20.05, 23.02]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1019.geometry}
				material={materials["Stem.028"]}
				position={[136.74, -20.05, 23.02]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1030.geometry}
				material={materials["Stem.028"]}
				position={[136.74, -20.05, 5.2]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1031.geometry}
				material={materials["Stem.028"]}
				position={[136.74, -20.05, -12.61]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1042.geometry}
				material={materials["Stem.028"]}
				position={[136.74, -20.05, -30.42]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1043.geometry}
				material={materials["Stem.028"]}
				position={[118.9, -20.05, -30.42]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1054.geometry}
				material={materials["Stem.028"]}
				position={[118.9, -20.05, -12.61]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1055.geometry}
				material={materials["Stem.028"]}
				position={[118.9, -20.05, 5.2]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1066.geometry}
				material={materials["Stem.028"]}
				position={[101.09, -20.05, 0.8]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1067.geometry}
				material={materials["Stem.028"]}
				position={[101.09, -20.05, -17]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1078.geometry}
				material={materials["Stem.028"]}
				position={[101.09, -20.05, -34.82]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1079.geometry}
				material={materials["Stem.028"]}
				position={[83.22, -20.05, -37.16]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1090.geometry}
				material={materials["Stem.028"]}
				position={[83.22, -20.05, -19.34]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1091.geometry}
				material={materials["Stem.028"]}
				position={[83.22, -20.05, -1.54]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1102.geometry}
				material={materials["Stem.028"]}
				position={[65.41, -20.05, 0.77]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1103.geometry}
				material={materials["Stem.028"]}
				position={[65.41, -20.05, -17.03]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1114.geometry}
				material={materials["Stem.028"]}
				position={[65.41, -20.05, -34.84]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
			<mesh
				geometry={nodes.Body1120.geometry}
				material={materials["Stem.028"]}
				position={[65.43, -20.05, 18.61]}
				rotation={[1.57, 0, 1.57]}
				scale={9.38}
			/>
		</group>
	);
}

useGLTF.preload("/stemClick.glb");
