/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import topHousing from "../../assets/keyboard/topHousing.glb";
import { useControls } from "leva";
export default function Model(props) {
	const { nodes, materials } = useGLTF(topHousing);

	const config = useControls("top housing", {
		visible: true,
		transparent: true,
		opacity: { value: 0.4, min: 0, max: 1, step: 0.01 },
		depthTest: true,
		depthWrite: false,
		alphaTest: { value: 0, min: 0, max: 1, step: 0.01 },
		side: {
			value: "THREE.DoubleSided",
			options: ["THREE.FrontSide", "THREE.BackSide"],
		},
		color: "#c0c0c0",
		emissive: "#000000",
		roughness: { value: 1, min: 0, max: 1, step: 0.01 },
		metalness: { value: 1, min: 0, max: 1, step: 0.01 },
		specularColor: "#ffffff",
		fog: true,
	});

	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Body1179.geometry}
				material={materials["top housing.017"]}
				position={[28.62, -18.99, 42.73]}
				rotation={[3.14, -0.47, 0]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1167.geometry}
				material={materials["top housing.017"]}
				position={[110.54, -18.99, 41.4]}
				rotation={[0, 1.29, 3.14]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1170.geometry}
				material={materials["top housing.017"]}
				position={[134.54, -18.99, 40.59]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1158.geometry}
				material={materials["top housing.017"]}
				position={[91.26, -18.99, 37.39]}
				rotation={[0.01, 1.48, 3.13]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1155.geometry}
				material={materials["top housing.017"]}
				position={[71.89, -18.99, 37.22]}
				rotation={[3.13, 1.52, 0.01]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1146.geometry}
				material={materials["top housing.017"]}
				position={[52.67, -18.99, 39.83]}
				rotation={[3.14, 1.36, 0]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1143.geometry}
				material={materials["top housing.017"]}
				position={[47.55, -18.99, 2.58]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1134.geometry}
				material={materials["top housing.017"]}
				position={[47.55, -18.99, -15.23]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1131.geometry}
				material={materials["top housing.017"]}
				position={[47.55, -18.99, -33.04]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1125.geometry}
				material={materials["top housing.017"]}
				position={[47.58, -18.99, 20.42]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1010.geometry}
				material={materials["top housing.017"]}
				position={[83.25, -18.99, 15.96]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1002.geometry}
				material={materials["top housing.017"]}
				position={[101.07, -18.99, 18.32]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1014.geometry}
				material={materials["top housing.017"]}
				position={[118.93, -18.99, 22.68]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1023.geometry}
				material={materials["top housing.017"]}
				position={[136.74, -18.99, 22.68]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1026.geometry}
				material={materials["top housing.017"]}
				position={[136.74, -18.99, 4.86]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1035.geometry}
				material={materials["top housing.017"]}
				position={[136.74, -18.99, -12.95]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1038.geometry}
				material={materials["top housing.017"]}
				position={[136.74, -18.99, -30.76]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1047.geometry}
				material={materials["top housing.017"]}
				position={[118.9, -18.99, -30.76]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1050.geometry}
				material={materials["top housing.017"]}
				position={[118.9, -18.99, -12.95]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1059.geometry}
				material={materials["top housing.017"]}
				position={[118.9, -18.99, 4.86]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1062.geometry}
				material={materials["top housing.017"]}
				position={[101.09, -18.99, 0.46]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1071.geometry}
				material={materials["top housing.017"]}
				position={[101.09, -18.99, -17.35]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1074.geometry}
				material={materials["top housing.017"]}
				position={[101.09, -18.99, -35.16]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1083.geometry}
				material={materials["top housing.017"]}
				position={[83.23, -18.99, -37.5]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1086.geometry}
				material={materials["top housing.017"]}
				position={[83.23, -18.99, -19.69]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1095.geometry}
				material={materials["top housing.017"]}
				position={[83.23, -18.99, -1.88]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1098.geometry}
				material={materials["top housing.017"]}
				position={[65.41, -18.99, 0.43]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1107.geometry}
				material={materials["top housing.017"]}
				position={[65.41, -18.99, -17.37]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1110.geometry}
				material={materials["top housing.017"]}
				position={[65.41, -18.99, -35.18]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
			<mesh
				geometry={nodes.Body1116.geometry}
				material={materials["top housing.017"]}
				position={[65.43, -18.99, 18.27]}
				rotation={[2.82, 1.57, 0.32]}
				scale={9.38}
			>
				<meshStandardMaterial {...config} />
			</mesh>
		</group>
	);
}

useGLTF.preload("/topHousing.glb");
